import type { Person } from './types'

export const MOCK_PERSONS: Person[] = [
    // HQ
    {
        id: 'hq-1',
        name: 'Trụ sở UBND Phường Bình Phú',
        type: 'HQ',
        kp: 'KP 1',
        address: '11 Hậu Giang, Phường Bình Phú, Quận 6, TP.HCM',
        yearJoined: 2000,
        lat: 10.7392,
        lng: 106.6267,
    },

    // TUOI_17 — red
    {
        id: 't17-1',
        name: 'Nguyễn Văn An',
        type: 'TUOI_17',
        kp: 'KP 3',
        address: '45 Bình Phú, Phường Bình Phú, Quận 6',
        yearJoined: 2022,
        lat: 10.7415,
        lng: 106.6255,
    },
    {
        id: 't17-2',
        name: 'Trần Thị Bình',
        type: 'TUOI_17',
        kp: 'KP 7',
        address: '12 Lý Chiêu Hoàng, Phường Bình Phú, Quận 6',
        yearJoined: 2023,
        lat: 10.7382,
        lng: 106.6295,
    },
    {
        id: 't17-3',
        name: 'Lê Minh Châu',
        type: 'TUOI_17',
        kp: 'KP 5',
        address: '89 Hồng Bàng, Phường Bình Phú, Quận 6',
        yearJoined: 2023,
        lat: 10.7428,
        lng: 106.6305,
    },
    {
        id: 't17-4',
        name: 'Phạm Quốc Dũng',
        type: 'TUOI_17',
        kp: 'KP 11',
        address: '33 Phan Văn Khỏe, Phường Bình Phú, Quận 6',
        yearJoined: 2022,
        lat: 10.7368,
        lng: 106.6248,
    },

    // QUAN_NHAN_DU_BI — blue
    {
        id: 'qndb-1',
        name: 'Hoàng Tuấn Anh',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 2',
        address: '7 Tùng Thiện Vương, Phường Bình Phú, Quận 6',
        yearJoined: 2018,
        lat: 10.7408,
        lng: 106.6240,
    },
    {
        id: 'qndb-2',
        name: 'Võ Thanh Hùng',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 4',
        address: '22 Bình Phú, Phường Bình Phú, Quận 6',
        yearJoined: 2017,
        lat: 10.7420,
        lng: 106.6275,
    },
    {
        id: 'qndb-3',
        name: 'Đặng Văn Khải',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 9',
        address: '55 Lưu Hữu Phước, Phường Bình Phú, Quận 6',
        yearJoined: 2019,
        lat: 10.7435,
        lng: 106.6260,
    },
    {
        id: 'qndb-4',
        name: 'Nguyễn Thị Lan',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 13',
        address: '101 Hồng Bàng, Phường Bình Phú, Quận 6',
        yearJoined: 2020,
        lat: 10.7395,
        lng: 106.6315,
    },
    {
        id: 'qndb-5',
        name: 'Bùi Công Minh',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 6',
        address: '68 Hậu Giang, Phường Bình Phú, Quận 6',
        yearJoined: 2016,
        lat: 10.7375,
        lng: 106.6282,
    },
    {
        id: 'qndb-6',
        name: 'Trịnh Hữu Nam',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 15',
        address: '14 Tùng Thiện Vương, Phường Bình Phú, Quận 6',
        yearJoined: 2021,
        lat: 10.7358,
        lng: 106.6265,
    },
    {
        id: 'qndb-7',
        name: 'Phan Thị Thu',
        type: 'QUAN_NHAN_DU_BI',
        kp: 'KP 10',
        address: '37 Phạm Đình Hổ, Phường Bình Phú, Quận 6',
        yearJoined: 2019,
        lat: 10.7445,
        lng: 106.6290,
    },

    // DQCD — green
    {
        id: 'dqcd-1',
        name: 'Lý Hoàng Phúc',
        type: 'DQCD',
        kp: 'KP 1',
        address: '3 Hậu Giang, Phường Bình Phú, Quận 6',
        yearJoined: 2015,
        lat: 10.7401,
        lng: 106.6258,
    },
    {
        id: 'dqcd-2',
        name: 'Ngô Thị Cẩm',
        type: 'DQCD',
        kp: 'KP 8',
        address: '76 Bình Phú, Phường Bình Phú, Quận 6',
        yearJoined: 2016,
        lat: 10.7412,
        lng: 106.6300,
    },
    {
        id: 'dqcd-3',
        name: 'Cao Xuân Định',
        type: 'DQCD',
        kp: 'KP 12',
        address: '29 Lý Chiêu Hoàng, Phường Bình Phú, Quận 6',
        yearJoined: 2018,
        lat: 10.7388,
        lng: 106.6235,
    },
    {
        id: 'dqcd-4',
        name: 'Đinh Thị Hoa',
        type: 'DQCD',
        kp: 'KP 14',
        address: '52 Hồng Bàng, Phường Bình Phú, Quận 6',
        yearJoined: 2020,
        lat: 10.7362,
        lng: 106.6310,
    },
    {
        id: 'dqcd-5',
        name: 'Mai Văn Sơn',
        type: 'DQCD',
        kp: 'KP 16',
        address: '88 Phan Văn Khỏe, Phường Bình Phú, Quận 6',
        yearJoined: 2017,
        lat: 10.7350,
        lng: 106.6280,
    },
]
